stages:
  - build
  - deploy

cache:
  key:
    files:
      - package.json
      - package.json.lock
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

npm install:
  stage: build
  image: node
  script:
    - export PUBLIC_URL=https://preview.snk.de/${CI_PROJECT_PATH} && npm run build
  artifacts:
    paths:
      - ./public
    expire_in: 10 mins

deploy:
  stage: deploy
  script:
    - echo ""
  tags:
    - projects-snk-de-runner